### ISSUE TITLE
Links between the rules peak_tf and compute_ins_chip non-existent

### ISSUE THREAD

**Issue by Connorr0** [settylab/atac_metacell_utilities#18]
In the current version there is no link between the rules peak_tf and compute_ins_chip. This appears to be because peak_tf is now updating the AnnData and compute_ins_chip never receives the output of peak_tf as an input.

This issue can be solved by adding the following to the input for compute_ins_chip:
`peak_tf = output_dir + "peak_tf/"`

**Comment by jordanc17** [comment]
Will be closed by #22 when merged.
